org: behealy
app: tut-serverless-api
service: tut-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-slimesTable-${sls:stage}
  environment:
    DYNAMODB_SLIMES_TABLE: ${self:service}-slimesTable-${sls:stage}

functions:
  createSlime:
    handler: slimeSpawn.create
    events:
      - httpApi:
          path: /
          method: post
  getSlimes:
    handler: slimeSpawn.get
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-slimesTable-${sls:stage}